### ISSUE TITLE
Using module-level global to set format and different API than other plugins

### ISSUE THREAD

**Issue by Xender** [chfw/pyexcel-text#1]
Hi.

Two similar issues:
- To specify a saved file format, one must modify a module-level global `TABLEFMT` variable.
  I feel that this module should and easily could be enclosed into class, with `TABLEFMT` being instance variable.
  - `save_as` could still be a module-level convenience function, but it should take the format as a mandatory argument.
    Module-level global `TABLEFMT` should be nuked.
- API is different than this of other plugins - pyexcel-ods, pyexcel-xls etc.
  One has to use `text.save_as(book, "myfile.rst")` instead of `sheet.save_as("another_file.ods")`.
  This is minor one, as one can argue that it's hard to determine the exact text file format based only on the extesion (or one might want a custom extension).

Thank you!

**Comment by chfw** [comment]
This plugin originally was made as a presentation plugin, that's why its API is a bit out of norm. I will harmonize the APIs of this module. So, your issues are accepted. Please wait for further notice.

**Comment by chfw** [comment]
Please evaluate the changes and let me know how it works for you. Please install latest pyexcel v0.1.6 and pyexcel-io v0.0.5 from github when you will do it.

**Comment by chfw** [comment]
Hold on. Build failed. Let me fix it first.
