### ISSUE TITLE
Load ndjson

### ISSUE THREAD

**Issue by jayvdb** [chfw/pyexcel-text#30]
[Newline delimitered JSON](http://ndjson.org/) is very popular for JSON streams.
It should be quite easy to support in this plugin, if we dont move JSON to a separate plugin.

**Comment by jayvdb** [comment]
Other various similar JSON formats are listed at https://en.wikipedia.org/wiki/JSON_Streaming

**Comment by chfw** [comment]
I would agree it is simple to support ndjson . Regarding the package, I would imagine pyexcel-json to do the read and write of json, ndjson. In terms of content structure, the following format can be considered as valid input as json: flat two demensional array(sheet), a dictionary of records(sheet) an a dictionary of two dimensional array(book). for ndjson, I think the following may be supported:

   [1,2]
   [3,4]

or 

   {"product": "cable", "price":20}
   {"product": "wire", "price": 10}
