### ISSUE TITLE
not compatible with pyexcel-io master

### ISSUE THREAD

**Issue by jayvdb** [chfw/pyexcel-text#4]
This extension causes an exception when installed with the master of `pyexcel` and `pyexcel-io`.

This prevents me using the master of `pyexcel` which doesnt have the bug https://github.com/pyexcel/pyexcel/issues/23

**Comment by chfw** [comment]
please do not use masters of pyexcel and pyexcel-io yet because pyexcel-io 0.2.0 is not yet complete. please use released version of both. When pyexcel-io 0.2.0 is ready, all plugins will be updated.

**Comment by chfw** [comment]
it's a known issue and a further re-write would happen when pyexcel-io 0.2.0 is to be released.
