### ISSUE TITLE
Add xml support

### ISSUE THREAD

**Issue by jayvdb** [chfw/pyexcel-text#5]
I would like to have a basic xml output, which 'does the right thing' to produce xml that can be easily used as an input to an XML pipeline.

`tabulate` has rejected adding an xml format

https://bitbucket.org/astanin/python-tabulate/issues/83/xml-format

fwiw, I would be happy to submit a PR for this feature, if this package maintainers believes it would be a useful addition.

**Comment by chfw** [comment]
Yes, I agree that xml is a useful addition. 

Because xml format will open the door for further manipulation by the use of xslt, I could see this addition will be spawn out as pyexcel-xml down the line. Let's see.

**Comment by jayvdb** [comment]
I managed to achieve my immediate objective without adding xml support to `pyexcel-text`, by emitting json and then using `dicttoxml`.  See
https://github.com/jayvdb/era_data/blob/master/fetch.sh#L30

I also evaluated `dict2xml`, and it is probably better for `pyexcel-text` because it returns unicode and doesnt emit the xml preamble , whereas `dicttoxml` emits encoded binary data with the xml preamble, which would cause a mess if there are multiple sheets.

**Comment by chfw** [comment]
previous commit was a wrong tag. closing this issue as json is enough.
